services:
  frontend:
    build: 
      context:
        ./frontend
      args:
        - VITE_API_URL=http://localhost:5000/api
        - VITE_AUTH0_DOMAIN=${AUTH0_DOMAIN}
        - VITE_AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
        - VITE_AUTH0_CLIENTID=${AUTH0_APP_CLIENTID}
    container_name: assisthub-client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
  backend:
    build: ./backend
    container_name: assisthub-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URI=mongodb://mongo:27017/assisthub
      - ADMIN_SECRET=${ADMIN_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_CLIENTID=${AUTH0_API_CLIENTID}
      - AUTH0_SECRET=${AUTH0_API_SECRET}
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: none
  
volumes:
  data:
    name: assisthub-data
    driver: local