name: Format source code and check for linting errors
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Format source code and check for linting errors
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix: { dir: ['frontend', 'backend'] }
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Check ${{ matrix.dir }}
        working-directory: ${{ matrix.dir }}
        run: |
          npm ci
          npm run prettier:fix
          npm run lint:fix
      - name: Commit formatting changes with Prettier
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes for ${{ matrix.dir }}
          branch: ${{ github.head_ref }}